- name: install system packages for wal-e
  apt: pkg={{ item }}
  with_items:
    - lzop
    - pv
    - python-pip
    - python-dev

- name: upgrade some python packages to fix the wal-e install
  pip: name={{ item }} state=latest
  with_items:
    - pip
    - requests
    - six

- name: Install wal-e via pip
  pip: name={{ wal_e_package_name }}

- name: render .profile for wal-e
  template: >
    src=profile.j2 dest=/var/lib/postgresql/.profile
    owner={{ postgresql_service_user }} group={{ postgresql_service_group }} mode=0750
